### ISSUE TITLE
Start business case/funding plan for Phase 4

### ISSUE THREAD

**Issue by vrajmohan** [18F/eligibility-rules-service#113]
The work to prepare a business case needs to begin. The work associated with the business case is not clear. We need to clarify what is needed and begin assembling those things.

**Acceptance criteria:**

- [ ] Define requirements for a business case for TMF
- [ ] Define requirements for a business case for 10x Phase 4

**Comment by edmullen** [comment]
The business case is underway. This story was aimed at signaling the start of the process, and it has met that.
