### ISSUE TITLE
Figure out a way to have video conferences for sprint demos and retros

### ISSUE THREAD

**Issue by vrajmohan** [18F/eligibility-rules-service#114]
FNS has trouble using Google Meet (Hangouts)

**Comment by edmullen** [comment]
Adobe connect, AppearIn, and hangouts do not work for FNS. Eliot and I had success using Zoom. For now, let's go with Zoom and see how it goes. It's unclear if DCF can use Zoom successfully.

**Comment by edmullen** [comment]
I've requested the pro zoom acct for all sprint ceremonies. Waiting to see if they're available.

**Comment by edmullen** [comment]
The rooms are reserved for the remainder of the project. For additional rooms request them in #admin-zoom
