### ISSUE TITLE
Paperwork Reduction Act review

### ISSUE THREAD

**Issue by vrajmohan** [18F/eligibility-rules-service#115]
Review the registration app data collected and ensure compliance with the PRA.

**Comment by vrajmohan** [comment]
Perhaps we should break this up into:

- [ ] Schedule the review for a subsequent sprint
- [ ] Complete the review

**Comment by vrajmohan** [comment]
For Sprint 3, run it by regulatory shop within FNS.

**Comment by edmullen** [comment]
For the current phase, the PRA will not apply. since we are testing with 9 or less states, we do not need to address PRA specifically.
