### ISSUE TITLE
Review and get initial sign-off on registration workflow and forms

### ISSUE THREAD

**Issue by vrajmohan** [18F/eligibility-rules-service#118]
Review and get sign-offs from:
- [x] FNS National Office
- [x] FNS South East Regional Office (SERO)
- [x] Florida Department of Children and Families (DCF)

**Comment by vrajmohan** [comment]
Focus is on confirming the data fields that we are collecting.

**Comment by edmullen** [comment]
[in progress comment]
This Issue has been completed. The following issues have been created to capture the conclusions. These issues will be prioritized and brought into sprints according to normal scrum practice.

- #165 Remove FEMA income type
- #164 Allow states to configure SNAP program names
- #163 Change to 3.1 household count screen
- #162 Remove 1.5 Off ramp screen
- #161 0.2 Get prepared screen changes
- #160 Move language selection
- #159 Rules change: applicant must be state resident

**Comment by edmullen** [comment]
With all the issues above created, I am closing this issue.
