### ISSUE TITLE
Define income types and follow-up questions

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#119]
On 5.2 Household member income, we need to define the income types and what questions we ask if that type is selected.

![image](https://user-images.githubusercontent.com/2654503/51992525-231a1500-247b-11e9-835d-6e19fd0569f2.png)

**Comment by vrajmohan** [comment]
Suggestion is to look for this in the handbook.

**Comment by edmullen** [comment]
I believe that I have a good solution sketched out, but I need to review it with the various parties.

![8 2 person income](https://user-images.githubusercontent.com/2654503/52802709-7cbf3980-304e-11e9-9015-93357ca216bd.png)

**Comment by vrajmohan** [comment]
Information obtained, needs to be reviewed along with #118.
