### ISSUE TITLE
DCF resourcing discussion

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#131]
While 18F is hoping to deliver as much completed work as we can, we know that DCF will need to be (and should be) the folks who handle certain aspects. We understand that this is an imposition, so we need to work with DCF to see what is possible and find solutions that will work for them. 

This is likely a separate conversation than #95.

**Comment by vrajmohan** [comment]
We will schedule a meeting with William and Jennifer to discuss the IT matter.

**Comment by edmullen** [comment]
After discussions with partners, Florida, National Office, and 18F have agreed that the best approach to proceed with regarding deployment that reduces the need for state technical resources will be to host the registration application at the federal government utilizing Cloud.gov.
