### ISSUE TITLE
(Design) Add path for users to elect not to persist form state in local storage

### ISSUE THREAD

**Issue by el-mapache** [18F/eligibility-rules-service#134]
In the case of a user applying for benefits at a public computer, we need to provide a mechanism for the user to choose not to store form data locally.

While this means the user will have to fill out the form from the beginning should they abandon the application before submission, it will also limit the possibility that the user will expose sensitive PII.

**AC**

- [x] Design/layout page (or section on an existing form step) that allows the user to choose whether or not to store form information locally, and informs them of the pros and cons of this choice

**Comment by edmullen** [comment]
Related to #166 and #168

The following fields are placed on a new screen, `.15 Set-up` along with a couple additional questions. See design guidance for further information.

### Design guidance

#### Flow

![0_15_-_info_you_ll_need_mobileflow](https://user-images.githubusercontent.com/2654503/53815299-66125100-3f2f-11e9-82d1-222b263801ae.jpg)

#### Screen detail

![0_15_-_info_you_ll_need_mobile](https://user-images.githubusercontent.com/2654503/53815158-159af380-3f2f-11e9-8e0f-3702e1d31a06.jpg)
