### ISSUE TITLE
Identify program

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#14]
# Question to answer

_Which human services program is the best candidate to develop as an example rules service?_

# Evaluating candidate programs

We need to select a human services program to build a rules service for. There are many factors to consider in this choice. We should be practical in our choice, but remain flexible to utilize our experience in selecting the best program. The following considerations should guide the selection.

### Is the program’s federal agency interested in partnership?
While we anticipate phase 3 collaboration with an agency to be lightweight and informal, we will want to choose a partner agency that is supportive, will provide subject matter expertise, and be open to further collaboration in the future, ideally as the product owner.

### Do users exist?
Are there states or other organizations with an existing need who would be interested in and capable of using the service, be available for user research, and be early users, to help us validate the general concept, the technical model, and the usability of our hypothesis?

### Could the service be stood up within a 10X Product Development phase of work?
We will want to emerge from the next phase with a functional rules service. If a program’s complexity impedes our ability to deliver within the given timeframe, it may not be a good candidate.

### Does an existing eligibility service already address this program?
If there is already a method for determining eligibility through a similar service, we should avoid duplication. For example, MAGI-Medicaid is already served by MAGI in the Cloud as well as the federal data services hub. 

### Would the service positively impact the program’s constituents to a significant degree?
We want this work to ultimately help the public. It’s reasonable to assume that some programs are in more difficult circumstances than others. We should consider the level of impact such a service could have on real people.

**Comment by alexpandel** [comment]
As indicated in #42, we've decided to move forward with WIC. Details about this decision are captured [here](https://github.com/18F/eligibility-rules-service/wiki/Determining-program-suitability#choosing-our-first-program-partner).
