### ISSUE TITLE
Create Step 3 - Household section page flow

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#144]
The Household section is the third step in the applicant experience. In this section, the household is established and information about each household member is asked.

**Comment by edmullen** [comment]
Design guidance defines the anticipated data inputs. Any changes will be reflected in new issues.

![household](https://user-images.githubusercontent.com/2654503/53031302-94296880-343a-11e9-97a4-e15c523d72cc.png)

**Comment by el-mapache** [comment]
@edmullen I merged code for this issue, but left out the current food assistance checkbox for the applicant, as it is going to require a bit of refactoring of both the data model and thee mechanism by which we store it in local storage

**Comment by edmullen** [comment]
@el-mapache OK, cool. Do you want me to make an issue for that specifically?

**Comment by el-mapache** [comment]
That would be great!

**Comment by edmullen** [comment]
Done: #152. And I have not been added it to the sprint.
