### ISSUE TITLE
Create Step 4 - Adverse section page flow

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#145]
The Adverse section is the fourth step in the applicant experience. In this section, the household's adverse effects are established.

**Comment by edmullen** [comment]
Design guidance defines the anticipated data inputs. Any changes will be reflected in new issues.

In the expenses section, the _Evacuation expenses_ expense type shows what should appear for all expense types once the user checks the check box: the secondary question _How much?_ appears along with a numerical input field.

![adverse](https://user-images.githubusercontent.com/2654503/53031544-0d28c000-343b-11e9-8aaf-4ae217c21e3f.png)

**Comment by el-mapache** [comment]
@edmullen Calling this `impact` currently (in the URL bar and code) as I feel that encapsulates what this section is a little bit better. Thoughts?

**Comment by edmullen** [comment]
yeah, that makes sense. the terms I've been using have been mostly just internal descriptions, but it's good you're looking out for clear naming.

**Comment by el-mapache** [comment]
@edmullen I've made a couple of changes to the copy for the questions that enumerate household member names. 

It seems unnecessarily cumbersome to have to interpolate a dynamic number of names, and add an additional label for the situations where the applicant has no additional members of their household.

This is the new copy I'm proposing:

'Did the disaster delay reduce, or stop the your income or the income of any of the other members of your household'

`Are you or any other member of your household unable to access some of your/their money?`

Eager to hear your thoughts!

**Comment by edmullen** [comment]
That's fine. Let's use this:

`Did the disaster delay, reduce, or stop the your income or the income of any of the other members of your household` (comma missing, my fault)

`Are you or any other member of your household unable to access some of your money?` (the your/their feels a bit clunky.)

I'll make sure these changes are in the content doc.
