### ISSUE TITLE
Define required fields and validation requirements in registration app

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#151]
We need to define all the fields that are required and what sort of validation is needed. Adam intends to do a validation pass through the app after completing the sections that precede the review.

**AC:**
- [x] All fields in the wizard are defined as required or not.
- [ ] All needed validation guidance has been provided.

**Comment by edmullen** [comment]
@vrajmohan I have taken a first pass of defining whether data inputs should be required or not based on what I currently know. I'd like to ask you to review those choices and make some changes. 

**AC**

- [ ] Any fields that ARE NOT CURRENTLY MARKED REQUIRED but ARE NEEDED to make a pre-determination, please change to required.

- [ ] Any fields CURRENTLY MARKED REQUIRED that are not required to make a pre-determination, please LEAVE AS IS. Some fields are required for state review purposes.

**Comment by edmullen** [comment]
@el-mapache Regarding validation, I'm not sure that I am equipped to do this well. Do you have a recommendation for how I should proceed to get you what you need?

The [content spreadsheet](https://docs.google.com/spreadsheets/d/1E2DXanrj3v48Y00OtKINk9i43b05QuAifnJnSFdVvK0/edit#gid=1474526559) has now been updated, is clean, and has a clear spot to add validation rules.

**Comment by el-mapache** [comment]
@edmullen I think what I was thinking was what messages we'd display for invalid data, and what constitutes valid data. For some things, like an email address, we know how to validate it. However, it gets a little more complicated for something like a date. Do we want to enforce leading 0s or do we allow single digits? Is there a minimum age an applicant needs to be to apply?

I do think that nearly all of the validations will simply be checking 'is this field filled in', but I'm sure there are other cases, like the date example above, that need further scrutiny.

**Comment by edmullen** [comment]
@el-mapache Yeah, that all makes sense, but I feel a bit rusty on best practice. I think most of the data types we collect, with the exception of adverse effects, are collected in the USDS prototype. I'd prefer to defer to their choices. (E.g. for birthdates, they do not seem to enforce leading 0s, but do enforce 4 digit years.)

I could go through an try to deconstruct what they've done, but do you know if there's a more efficient way to extract that from the proto?

**Comment by el-mapache** [comment]
Ahh, I didn't realize we could just follow the validations from the prototype. Unfortunately, they still have to be manually extracted, but it seems like something I'll have to do since it's going to require pulling apart their code.

**Comment by edmullen** [comment]
I don't mean to increase your workload. Let's chat tomorrow at standup.

**Comment by edmullen** [comment]
The content document now has all the required fields, validation rules, and English error messages included. Closing.
