### ISSUE TITLE
Rules change: applicant must be state resident

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#159]
Related to #168 

States can only issue SNAP benefits to state residents. The rules already meet this criteria when the state only allows applicants who lived in the affected area. But if the state allows people who are affected because the worked in the area, we are not currently checking that those people reside in the state. 

We already capture the data to determine this, but there is not a rule specifically calling it our.

**Comment by vrajmohan** [comment]
The state in the residential address of the registration should be equal to the state associated with the disaster.
