### ISSUE TITLE
Remove 1.5 Off ramp screen

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#162]
It turns out that the `1.5 Off ramp` screen creates a number of IRL problems:

- registrations with such minimal data deliver very little value to anybody
- the attestations would be made before the overall registration has been filled out and there's no means to redo that
- completing the incomplete registrations would prove more difficult that just starting fresh
- the requirement to allow people to apply with such minimal information does not apply to our situation since the form is a registration, not an application

To remedy the situation, we are removing the off-ramp concept from the flow, along with the ability to submit a partial registration. We will use this as an informational page only.

**AC**

- [ ] Remove the green box message

**Comment by edmullen** [comment]
Adam suggests that we retain the screen as a pause point but remove the branching construct.

**Comment by el-mapache** [comment]
@edmullen without the option to stop working and submit immediately, does this copy still make sense?

```
You are legally allowed to submit your application with your name and address. This will take longer as we will mail you the rest of the paperwork to complete.
```

I don't think we have any way for a user to submit what they have at this point and elect to receive something in the mail, given the options on the page.

**Comment by edmullen** [comment]
No, it does not make sense, but we'll write something else for that space as part of finalizing content and change it when we put all the final copy in. 

In other words, we'll reuse that content space and say something else.
