### ISSUE TITLE
Add disaster description to rules service configuration, API

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#187]
We need to add a disaster description to the configuration of a disaster. This is used to make the user clear they are selecting the right disaster.

**AC:**

- [x] An administrative user can add a brief description in a disaster configuration
- [x] The description available from the GET endpoint

**.15 Set-up mock**
![image](https://user-images.githubusercontent.com/2654503/54623817-a51dc780-4a42-11e9-9df7-faa596ddf6fe.png)

**Comment by vrajmohan** [comment]
The disaster `title` can be 50 characters long. How big do we want the `description` to be? @edmullen?

**Comment by edmullen** [comment]
How about 100?

**Comment by vrajmohan** [comment]
Fixed through https://github.com/18F/dsnap_rules/commit/de92863077ce230595469c6029ada6f7f40439ba
