### ISSUE TITLE
Change state agency to D-SNAP agency in the registration service

### ISSUE THREAD

**Issue by vrajmohan** [18F/eligibility-rules-service#196]

**Comment by vrajmohan** [comment]
Fixed by https://github.com/18F/dsnap_registration_service/commit/67dcc39fbb8fb758f77d2493e8584ffcf3672f71.

**Comment by el-mapache** [comment]
Fixed on the FE by [18F/dsnap-registration@71540df](https://github.com/18F/dsnap-registration/commit/71540dfb1ef7cccfcd68d27a3d876adebe19d768)
