### ISSUE TITLE
Add disaster description to the front-end

### ISSUE THREAD

**Issue by el-mapache** [18F/eligibility-rules-service#198]
On the pre-registration screen, when the user is selecting a disaster, we should display a brief description of the disaster, to help the user make the correct choice

**AC**
- [x] Show description of the disaster, as returned from the endpoint. See sketch file

**Comment by el-mapache** [comment]
@edmullen One thing to think about is that the disaster description won't be localized by default. We don't really have a method to do that in the admin at the moment. It probably doesn't matter for this phase, but is additional work to keep in mind for the future.

**Comment by edmullen** [comment]
I don't quite follow. A "disaster" in our config is state-based. So If a hurricane hits FL and GA, there will be two different disasters set up, each one specific to a state. So if this happened currently, we'd have something like:

- [ ] **Hurricane Edward (Florida)** For Florida residents affected by Hurricane Edward in the panhandle
- [ ] **Hurricane Edwarda (Georgia)** Georgia residents affected by flooding after Hurricane Edward.

What kind of localization are you thinking about?

**Comment by el-mapache** [comment]
@edmullen I can see why this would be confusing, since we are dealing with disasters localized to physical areas in a state! My comment was meant to address localization as in `i18n`.

I'm raising the issue of a spanish-speaking user selecting `spanish` as their preferred language and seeing disaster descriptions in english.

**Comment by edmullen** [comment]
ohh, yes. hmm. You are absolutely correct! We'll create an icebox issue. That's a great point.
