### ISSUE TITLE
Schedule background conversation with Robin and Jessie P

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#22]
Let's get time on Robin and Jessie's calendar to discuss our previous work with ACF, FNS, and CMS.

Target 30 mins in the middle of the week of Jan 2

**Comment by shawnique** [comment]
@edmullen are you referring to Jessie Posilkin

**Comment by edmullen** [comment]
Yep.

**Comment by shawnique** [comment]
Jessie suggested we talk to  Nikki L., Mark H., Vicki M. 
I'll see if they are available during that week as well?
