### ISSUE TITLE
Worker: Search interface

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#222]
**AC:**
- [x] worker can submit search query to registration service
- [x] On successful search, we'll return list of matches
- [x] When worker selects a search result item, they are routed to correct registration
- [x] On unsuccessful search, we'll return a message accordingly

**Comment by edmullen** [comment]
@Adam will take a look at what Vraj has put together in the search endpoint and we'll discuss how to proceed.

**Comment by el-mapache** [comment]
We decided to allow the worker to search using the fields predefined by @vraj and noted in the registration service README [here](https://github.com/18F/dsnap_registration_service). Design guidance will follow existing form layouts.
