### ISSUE TITLE
Dig into WIC eligibility requirements

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#23]
So far, WIC seems like a good candidate. We need to better understand how eligibility for WIC works in order to make a more definite call. In particular, I'm interested in learning more about the scale of the eligibility criteria. One of our selection criteria for a program is to be able to build out an initial version of the service during the next stage. So I'd like to know how many factors applications are evaluated upon. If possible, I'd also like to know more about the variation across states. 

SNAP has a [state options report](https://drive.google.com/drive/folders/1ryblRT1sIRq4AI-ADPSGxw7c1nW22voC) which is very helpful. Maybe something like that exists for WIC.

To be sure, these are big questions that can't be _fully_ answered now. In fact, this is why we want a partnership. We just need to be better informed than now. So let's just scope this as what you can find this week and then we'll reassess next week.

**Comment by shawnique** [comment]
WIC Eligibility Doc[](https://docs.google.com/document/d/179SBfzbFSwTeBRLID8STjL0Hu-YGWRgiiZQC3qL6OAU/edit#)

**Comment by edmullen** [comment]
@shawnique Let's post the contents of that Google Doc here for visibility.

**Comment by shawnique** [comment]
**WOMEN, INFANTS, AND CHILDREN (WIC) NUTRITION PROGRAM**

**Mission:** To provide free support to low-income pregnant, breastfeeding and post-partum women and children under age five who are considered to be at nutritional risk.

**[WIC ELIGIBILITY](https://www.fns.usda.gov/wic/wic-eligibility-requirements)** 

**Income Eligibility:**
Gross income, must be less than or equal to 185% of the [Poverty Income Guideline](https://fns-prod.azureedge.net/sites/default/files/wic/WIC-IEGS-2017.pdf). Which is currently about $876 a week for a family of four

**Health Eligibility:**
Applicants must be seen by a health professional such as a physician, nurse, or nutritionist who must determine whether the individual is indeed at nutrition risk. 
In many cases, this health screening is done at no cost to the applicant.
Receiving other services:
Those who are eligible to receive SNAP benefits, Medicaid, or TANF automatically meet the income eligibility requirement.

**APPLY FOR WIC**
The [WIC Prescreening Tool](https://wic.fns.usda.gov/wps/pages/start.jsf) is often used to determine if folks are eligible for WIC benefits. This online tool will ask for the amount the household earned (wages, tips, etc.) and unearned income (child support, unemployment benefits, SSI, etc.).
To apply for WIC, people can contact a local WIC office to set up an appointment. Once approved recipients usually receive aid in the form of checks, vouchers, or electronic benefit cards.

**Appendix**
[WIC Fact Sheet](https://fns-prod.azureedge.net/sites/default/files/wic/WIC-Fact-Sheet.pdf)
