### ISSUE TITLE
Worker: Research for sign in

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#230]
We need to understand what's involved with the most basic authentication we can find.

**AC:**

- [x] Plan for authentication

**Comment by vrajmohan** [comment]
I was able to create an initial implementation as well. This is not merged and is available in the branch https://github.com/18F/dsnap_registration_service/tree/add-auth.

**Comment by vrajmohan** [comment]
Implemented through https://github.com/18F/dsnap_registration_service/commit/a7c0b02cc5681bd74dab6e1291d046d6fb2c3eb3
