### ISSUE TITLE
Create endpoint for approving/denying D-SNAP applications

### ISSUE THREAD

**Issue by vrajmohan** [18F/eligibility-rules-service#240]
@edmullen, should the EBT number go with the approval or should it be a separate operation? If the latter, can you provide an EBT number for an application that is not approved?

**Comment by edmullen** [comment]
They should be separate operations.

For the endpoint, you should be able to save it for an application that is not approved. On the frontend, there isn't currently a way to save whatever you type in the field without hitting approve or deny, but that could change in the future.

**Comment by vrajmohan** [comment]
Also save the original determination from the rules service, the user making the (override) determination and the timestamp.

**Comment by vrajmohan** [comment]
Fixed through https://github.com/18F/dsnap_registration_service/commit/dd54efc8795905e2dada5a9e92441920206c219f
