### ISSUE TITLE
Income data not saved locally when user goes back, forcing them to re-enter data

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#243]
- Observed: In private computer/save locally mode, the reg app behaved differently for income data than for other data in the form. When the user went back to the beginning of the app and proceeded to move forward from the beginning, the reg app retained most of the field information allowing the user to navigate to the point they were looking for. This was not true for income data, however. The income fields were blank, requiring the user to resubmit that data.
- See [SERO A-1 25:00](https://drive.google.com/open?id=1w7ZV8oYhovbwLgMIf2h33QJCcF_5LXCF)

**Comment by el-mapache** [comment]
@edmullen Watching this video I am slightly confused. It was just money on hand that was blank, correct? It looked like the other income type fields were persisted correctly

**Comment by el-mapache** [comment]
Closing as I believe this issue has been resolved
