### ISSUE TITLE
Wizard skipping one household member’s income screen

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#245]
- Observed: The user indicated that two people in the household, including the registrant, earned income but when the user proceeded to the next screen to add income details, the wizard skipped the registrant and went right to the next person in the household. When the user moved to the next step, it did not ask about the registrant income after.
- This did not happen each time
- See [SERO B - 1 48:25](https://drive.google.com/open?id=10DUY-4qEFWNucZAsO0SHqxVqaFGT9Njp) (error); [SERO B - 1 30:25](https://drive.google.com/open?id=10DUY-4qEFWNucZAsO0SHqxVqaFGT9Njp) (no error)

**Comment by el-mapache** [comment]
@edmullen Let me know if you observe this in your testing session today. I _think_ this behavior should be handled with the new changes, assuming the dev branch is stable enough to fully test.

**Comment by edmullen** [comment]
I did not see this behavior again. We only got through one registration though. You can see it here: https://drive.google.com/open?id=1l0QRyWSxmI-boxP0GbiwveUffTRUplRD starting at 28:00. 

I really don't know what triggered the behavior before thought, because it was not happening each time.

**Comment by el-mapache** [comment]
@edmullen I reviewed the video again, and if you watch closely, it looks like the tester accidentally unchecked the first name in the list of income recipients.

Check out this screenshot. I redacted thee info, although Im pretty certain it's  dummy data
![video-testing-unselect](https://user-images.githubusercontent.com/1421848/56584946-d68e3380-65aa-11e9-95b2-99edcd4dd8a5.jpg)


I think this is probably why the behavior is not reproducible / consistent

**Comment by edmullen** [comment]
oh, you're right. Very weird. It does look like it go unchecked on that screen, but it's hard to see her cursor do that. Odd. It appears to be on the other side of the screen at the time. 

OK, I think we should probably set this issue aside then and see if it comes up again later as some unintentional deselecting matter. 

If you agree, go ahead and close this.

**Comment by el-mapache** [comment]
Pretty sure that with the screen at that width, the checkbox label is taking up 100% of the width of the screen, so when the tester makes a stray click, thee field is geetting unchecked.

This normally isn't a problem because a user would generally only have a smaller width screen on a phone, where it is a little harder to accidentally produce a stray click (since the phone has to distinguish between a scroll and touch event)
