### ISSUE TITLE
Registration app gets locked down from moving forward

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#246]
- Observed: There is a weird situation that is better watched than described. 
- See: [SERO B-1 14:45](https://drive.google.com/open?id=10DUY-4qEFWNucZAsO0SHqxVqaFGT9Njp)

**Comment by el-mapache** [comment]
@edmullen This should be resolved with the new code on prod!

**Comment by edmullen** [comment]
I have not seem this myself recently, so it does appear to be resolved.
