### ISSUE TITLE
Chrome autofills on SSN, etc

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#248]
- **Observed:** When the user restarted a new session in Chrome Incognito mode, she went through filling in data. When it came to the Identity screen for the registrant, Chrome presented an autofill suggestion for SSN. 
- Recommendation: I believe that we can suppress this function in Chrome and think we should do this for SSN at minimum, and consider the appropriate approach for other fields. 
- See [SERO B-1 23:35](https://drive.google.com/open?id=10DUY-4qEFWNucZAsO0SHqxVqaFGT9Njp)

**Comment by el-mapache** [comment]
@edmullen unfortunately, chrome seems to have autofill on by default. There are a couple more tricks I can try out on the front end, but it seems like the user has to explicitly disable autofill in chrome.

**Comment by edmullen** [comment]
@el-mapache will look at the matter and make a call about whether anything should be done on this now.
