### ISSUE TITLE
Make it clearer how the user should answer the “how many people do you buy and share food with” question

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#249]
- **Observed:** It is unclear to the user if they should re-enter the registrant info on the household building screen. 
- One user assumed “person 1” would be the registrant and began refilling out the registrant’s info. It seemed redundant to have to fill that first person out again. I intervened at that point. 
- The other user wrote the total number of people, including the registrant, but then on the following screen, did not add the registrant duplicatively, but then had an extra person section that was required. They had to go back to correct the number of people.
- See SERO A-1 13:30; SERO B-1 13:35
- **Action:** 
    - Update the language on the Household count screen to be very clear we’re asking “in addition to [registrant name]
    - On _Household member names_, display the registrant’s info on-screen under the heading “Person 1” and then have the additional people start with “Person 2”.

**Comment by edmullen** [comment]
@el-mapache Here's what I'd like to propose. Tell me what you think.

**1. On 3.1 Household number**
- [ ] We change question to add ", including yourself?"
- [ ] We change our input notion to including the registrant (instead of excluding them as we currently d)
- [ ] We change the input to a select menu with the following options:
    - Just me
    - 2 people
    - ... (3-11 people)
    - 12 people

**2. On 3.2 People in household** - use still only sees if they previously answered 2 or more)
- [ ] Tweak language a bit
- [ ] We populate the registrants name as Person one. See Mockup below:

![3 2 - People in household](https://user-images.githubusercontent.com/2654503/56501894-877acc80-64de-11e9-849a-f0d89e27d5d2.png)

**Comment by el-mapache** [comment]
@edmullen Changing the language to read 'including yourself' and making the first entry a read-only field with your information seems like a great first test. I'm not sure if changing multiple things in a single iteration is the way to go; maybe we can add the dropdown after a future session. Unless you think it's just better UX in general to use a dropdown!

Why are we including the DOB for the registrant on this screen?

**Comment by edmullen** [comment]
The change is based on looking at GetCalFresh.org:

![image](https://user-images.githubusercontent.com/2654503/56585931-c2e3cc80-65ac-11e9-9973-e65922b89007.png)

I think their use of "just me" in the menu reduces quite a bit of ambiguity on that first screen. But if you want to try it just changing the language and including the person's name on the second screen, that's fine. We can try that first.

I included the DOB thinking about people with the same names in a family. I don't know that it's necessary. I have no evidence of it. If you think we should just try with the name until we see an issue, I'm fine with that too.

**Comment by el-mapache** [comment]
Ahh I see. I like this, seems like a pretty clean pattern. I do think the 'Just me' is super clear as well. Should we also add this explanatory text for spouses, children, etc?

**Comment by edmullen** [comment]
Yeah, they did a nice job. So what are you thinking? Do you want to adjust the input too?

We shouldn't include that text because it's specific to them. That's not true for us.
