### ISSUE TITLE
Update English and Spanish content

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#269]
- [x] Update English content in the JSON file
- [x] Update Spanish content in the JSON file

**Comment by el-mapache** [comment]
Almost all the content has translations! Only the following strings are still missing from the document:

* phone number error translation
* You didn't indicate any other members of your household 
* Self-employment income
* Clear session and quit
* Add job
* Stop editing
* Something went wrong with your submission. Please wait a moment and try again
* Update
* Add job
* Add new household member

**Comment by el-mapache** [comment]
Another issue I noticed was this copy on the welcome screen:

```
Payment for disaster expenses you don’t expect to get reimbursed for by [end of benefit period]. 
```

I think we should just have the literal string 'end of the benefit period' here, since we don't actually know what disaster the user is applying for at this point in the workflow

**Comment by edmullen** [comment]
That makes sense. Looks like we need the translation for that too. I'll add it to the list.

**Comment by edmullen** [comment]
These last pieces are now available in the content spreadsheet here: https://docs.google.com/spreadsheets/d/1E2DXanrj3v48Y00OtKINk9i43b05QuAifnJnSFdVvK0/edit#gid=1474526559&range=764:773
