### ISSUE TITLE
Kickoff meeting

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#3]
We're ready to have the project kickoff call. 

**Acceptance criteria**
- [x] Schedule call
- [x] Meeting prep
- [x] Conduct call
- [x] If needed, create issues for any follow-ups from meeting

**Comment by edmullen** [comment]
@nicopapafil, we're ready for you to schedule the kickoff the project team and @abisker (I believe)

@alexpandel and I have spoken. @shawnique and I will be talking later today, so we'll be ready after today.

**Comment by abisker** [comment]
Since we'll be moving CPS off of these 10x engagements, @nicopapafil have you and Lane identified who will be the account manager on this (i.e., the person I should hand this issue + the burn doc off to?). Thanks!
