### ISSUE TITLE
Technical review of MAGI in the Cloud

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#34]
Look at the code for MAGI in the Cloud and develop and orientation for how they approach things. 

AC

- Review the codebase
- Provide high-level review for the team
- Develop questions for BlueLabs

**Comment by catherinedevlin** [comment]
Document underway:

https://docs.google.com/document/d/19_hsvvFpv6pAYjHo4kwq6U4cXzp3107uwEYfx8cJAic

**Comment by catherinedevlin** [comment]
I feel ready to move this to "Done" - @edmullen , do you agree?

**Comment by edmullen** [comment]
If you know what questions you'd like to ask BlueLabs, then yes. If not, maybe spend a few minutes to pull that together before closing.

**Comment by catherinedevlin** [comment]
OK, I'm planning to ask them their experience/thoughts on 

- Versioning of rules
- How to manage and delegate rulemaking authority 
- Any PII concerns (real or imagined)
- Logging of requests & responses
