### ISSUE TITLE
Onboard Catherine

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#36]
Catherine is scheduled to begin Feb 19. We will need to help her get up to speed on the project.

**Comment by shawnique** [comment]
Onboarding 2/19

**Comment by shawnique** [comment]
Introducing Catherine to the project. We'll go through these items during our onboarding call.

**Shawnique's acceptance criteria**

- [] Conduct onboarding call
- [] High level project overview and backstory
- [] Staffing / time commitment
- [] Rituals - Planning meeting, slack standups, working in open, etc.
- [] GitHub repo / project board
- [] Walk through E&E Drive folder
- [] Overview of anticipated work
- [] Collaboration expectations (what helps you do your best work)

**Cathrine's acceptance criteria**

- [] Review overall readme - https://goo.gl/WBiu6s
- [] Phase 1 Conclusions docs - https://goo.gl/LuVZqQ , https://goo.gl/WLC17Y
- [] Phase 2 folder & docs - https://goo.gl/Kdn7M3
- [] Review Phase 2 readme - https://goo.gl/t6Atxm
- [] Review human services overview
