### ISSUE TITLE
Learn about OPA, OPA -style systems

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#38]
We need additional information about other players in the field.

**Comment by catherinedevlin** [comment]
Review underway:

https://docs.google.com/document/d/16AifdME4w2XGYVPjRBBy8ZiGFVDlsRb2cSwG0ZoIg7s/edit

Feature matrix:

https://docs.google.com/spreadsheets/d/1emdrykNwHdN2QASCtxwYl3rmpPsN8jmHQ_h-6zqS1uA/edit#gid=0

**Comment by catherinedevlin** [comment]
I feel ready to move this to "Done" - @edmullen , do you agree?

**Comment by alexpandel** [comment]
@catherinedevlin - would you be up for capturing a brief sentence in here stating the conclusion you drew from your review, and then you can close it?

**Comment by catherinedevlin** [comment]
@alexpandel - the full notes are at https://docs.google.com/document/d/16AifdME4w2XGYVPjRBBy8ZiGFVDlsRb2cSwG0ZoIg7s, but for an overall conclusion I'd say:

OPA is a heavyweight solution that would lock us into a very specific structure with high overhead to host and maintain, and with a variety of features that our intended solution does not need.  The costs would outweigh the benefits.

Thanks!
