### ISSUE TITLE
Decide on federal partner

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#42]
This is done when: 

- [x] we've decided amongst ourselves what makes the most sense
- [x] we've notified each potential partner of our decision and next steps
- [x] we've updated the repo with this decisions and our reasoning

**Comment by edmullen** [comment]
Shawnique and I discussed how we may not need to pick a partner just yet, but could further dig into the policy requirements of potential programs before deciding.

**Comment by edmullen** [comment]
We anticipate making a decision on agency partner at the end of this week.

**Comment by alexpandel** [comment]
Added our thinking about our decision to move forward with WIC [here](https://github.com/18F/eligibility-rules-service/wiki/Determining-program-suitability#choosing-our-first-program-partner).
