### ISSUE TITLE
Initial policy research session with CMS policy folks

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#43]
We can begin planning for an initial conversation with CMS policy folks to get deeper info on the program options.

**Acceptance criteria**

- [x] prep agenda
- [x] prep questions
- [ ] schedule meeting (Ed)
- [ ] conduct session
- [x] next steps post meeting

**Comment by edmullen** [comment]
I will follow-up w CMS and try to schedule

**Comment by edmullen** [comment]
@shawnique I started this doc to drop a question I have. You could use this going forward: https://docs.google.com/document/d/16Os7WeuVnA3r7j0c7rQyZpxdtx5RFolw9chZDJXvcVU/edit#

**Comment by shawnique** [comment]
**CMS Policy Folks Agenda**

- Explain what we are looking to do:
    [ ] Identify a program with the 
         [ ] least requirements 
         [ ] least amount of state variation
         [ ] least amount of uncertainty 
- Request a brief run through of MAGI Eligibility
- Identify the different non MAGI Eligibility Requirement
- Discuss the different Pathways 
- Identify Steps moving forward

**Comment by shawnique** [comment]
CMS has not responded to our request. Will follow up at a later time

**Comment by shawnique** [comment]
Randy Shared the [VermontAHS/AHS-Business-Rules-Repository](https://github.com/VermontAHS/AHS-Business-Rules-Repository). Although we've put CMS on the back burner for the time being,  It may be interesting to review how Vermont has broken down their eligibility rules into plan language.

**Comment by edmullen** [comment]
We have selected the WIC program with FNS. Closing this card.
