### ISSUE TITLE
Learn for which programs DC Health Link determines eligibility

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#45]
The DC Health Benefit Exchange / DC Health Link is an open source multi-benefit E&E system. We should talk with them to learn more.

**Comment by shawnique** [comment]
DC Health Link Doc[](https://docs.google.com/document/d/15E1g2LqN-XOLXf-ABUMBFb9b514OKh4VwpeDb2QlVtM/edit)

**Comment by shawnique** [comment]
Spoke with Randy H. and Vicki M. yesterday and they are currently working on a similar project with the state of Vermont. 

Their project team conducted did a small project, doing code base research on DC Health Link E&E system. Vicki informed me that this research will  be available within the next couple of days, and would make it available for us to review.

**Comment by edmullen** [comment]
This work was deemed no longer necessary for this phase.
