### ISSUE TITLE
Distill WIC eligibility criteria

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#55]
We need to get WIC's eligibility manual (or something like that) that allows us to distill the federal requirements for WIC.

This is done when:

- [ ] federal requirements have been translated from policy-speak to human-speak.

**Comment by edmullen** [comment]
We've received a number of useful docs to sort this out. See https://docs.google.com/document/d/1XikORXHl6jSy1DUKJL8XjyIjUAks3tLJ_fXfurXkpoA/edit#bookmark=id.oy5m3kbnrjc6

@shawnique You should be in good shape to more forward with this.

**Comment by shawnique** [comment]
https://docs.google.com/document/d/179SBfzbFSwTeBRLID8STjL0Hu-YGWRgiiZQC3qL6OAU/edit#heading=h.ie44qb2hkz6l

**Comment by edmullen** [comment]
We are "pens down" on our distillation. While not perfect, it is sufficient for our purposes and time.
