### ISSUE TITLE
Determine front-end form approach

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#59]
For the purposes of demonstrating the functionality of the rules service, we'll need to connect it to a front-end interface to submit data. There are several existing options we could use to start with, including the [School Meals application prototype](https://www.fns.usda.gov/apps/school-meals/web-based-prototype/docs/index.html#), the [multi-benefit application prototype](https://usds.github.io/benefits-enrollment-prototype/), and [docassemble](https://docassemble.org/), among others.

This issue is done when:

- [x] Alex & Ed have discussed the various options
- [x] we've decided which direction to pursue
- [x] we've made any follow-up issues as needed to carry out the work

**Comment by alexpandel** [comment]
In our convo yesterday, @edmullen & I landed on taking a basic page from either the [School Meals application prototype](https://www.fns.usda.gov/apps/school-meals/web-based-prototype/docs/index.html#) or the USDS/18F [multi-benefit application prototype](https://usds.github.io/benefits-enrollment-prototype/) (which use USWDS) and building out whatever screens we need with minimum customizations or fanciness.

@edmullen, I'll leave it to you to create any follow-up issues for this and close this one when you're ready!

**Comment by edmullen** [comment]
Created #63 to complete this work.

**Comment by edmullen** [comment]
Reopening because @catherinedevlin mentioned she may have a tool to help build this faster.

**Comment by edmullen** [comment]
Catherine knows how we'll proceed. More info to come.
