### ISSUE TITLE
Prepare for program candidate evaluations

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#6]
We will need to evaluate which program candidates are best suited for the exemplar. We'll need to define the criteria we use and create a place to gather that data we gather.

**Comment by edmullen** [comment]
I created an [initial draft](https://docs.google.com/document/d/11kWr8U4er5fUKmUDQaQNWMuPGAHAT8Lu4J1ViZooEf4/edit#heading=h.m9euqor5ysox) here that's ready for review @alexpandel. I'm sure you'll have a number of thoughts. Let's continue discussion in the Google doc. When we're set, I'll post it in GitHub.

**Comment by alexpandel** [comment]
This looks great, @edmullen! I suggested some changes in the doc, but they are opinionated, so feel free to roll 'em back, and/or we can discuss later today!
