### ISSUE TITLE
Plan for Phase 3 funding request

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#60]
We need to plan for our next funding request.

This is done when:
- [ ] we've taken a first pass at articulating our product strategy
- [ ] we've taken a first pass at fleshing out what we can of the [10x phase 3 pitch template] based on our product strategy (https://docs.google.com/presentation/d/1L4WRCWdECzJRBtNUudb7-SWUUyCcJSyDurBOwDQyp58/edit)
- [ ] Ed & Alex have made time to talk through the pitch first draft and flesh out any remaining pieces we need
- [ ] we've identified and captured in follow-up issues any outstanding questions we need to answer or other work we need to do to get the pitch in good shape

**Comment by alexpandel** [comment]
Updated the definition of done for this task based on our convo yesterday @edmullen. I'm gonna let you take a first pass, but feel free to tag me in when you need a second brain!

**Comment by edmullen** [comment]
Based on the AC, this is complete, though the pitch is still fluid.
