### ISSUE TITLE
Build RESTful service structure

### ISSUE THREAD

**Issue by catherinedevlin** [18F/eligibility-rules-service#61]
Without incorporating any actual eligibility rules, build a skeletal RESTful web service that accepts POSTed payloads of hypothetical applicant data and returns a JSON document of (fake) eligibility determinations.

Should include

- [x] Test harness
  - [x] Unit tests
  - [x] Integration tests
  - [x] Property based testing 
- [x] Deployment to cloud.gov sandbox
- [x] Instructions for development deployment 
  - [x] Dockerfile and instructions
- [x] Integration with CodeClimate

**Comment by catherinedevlin** [comment]
The structure is working, and serving results for one rule (documented income eligibility) - see instructions at https://github.com/18F/eligibility-rules-service/tree/master/eligibility_rules_server

**Comment by edmullen** [comment]
This has been done. Closing.
