### ISSUE TITLE
Implement AND/OR interactions of rules

### ISSUE THREAD

**Issue by catherinedevlin** [18F/eligibility-rules-service#65]
First pass at the server evaluates multiple rules joined by AND, but we should support rules that relate by OR (like "Adjunct or Automatic Income Eligibility" OR "Documented Income Eligibility / Income standard"), and trees of nested logic: (a OR (b AND (c OR d)))

**Comment by edmullen** [comment]
@catherinedevlin any updates or changes? If this is not something you anticipate pursuing, let's either close this or move it to backlog to think about in the future.

**Comment by edmullen** [comment]
@vrajmohan I believe we should close this issue since it relates to the previous codebase. Do you agree?

**Comment by vrajmohan** [comment]
Agreed.
