### ISSUE TITLE
Make rule-writing easier

### ISSUE THREAD

**Issue by catherinedevlin** [18F/eligibility-rules-service#66]
The SQL rules interpreted by the engine need a lot of work to make them easy to write and troubleshoot.

- [x] Document how the rules work
- [x] `/rules` endpoints outputting a description of the rules used 
- [x] Validator to show rules errors & give feedback without running through server
- [x] Unique constraints to avoid accidentally making duplicate rules

**Comment by edmullen** [comment]
@catherinedevlin any updates or changes? If this is not something you anticipate pursuing, let's either close this or move it to backlog to think about in the future.

**Comment by catherinedevlin** [comment]
Just marked the validator as done, and I'll do some documentation today (though, let's be honest, documentation is never truly done).  Upon reflection, "Command to duplicate a ruleset and its dependent rules" seems more trouble than it's worth; cut-and-paste works fine.  "Unique constraints to avoid accidentally making duplicate rules" I can throw in quickly.  So I think I can finish this today.

**Comment by edmullen** [comment]
@vrajmohan I believe we should close this issue since it relates to the previous codebase. Do you agree?

**Comment by vrajmohan** [comment]
Agreed.
