### ISSUE TITLE
Version rulesets

### ISSUE THREAD

**Issue by catherinedevlin** [18F/eligibility-rules-service#68]
Because rulesets will change with time, the server should store multiple versions of a ruleset and use the one specified by a version name or an effective date, defaulting to the version currently active.

**Comment by edmullen** [comment]
@catherinedevlin This story is in our backlog. Is there value in keeping it in the backlog for the future or not?

**Comment by edmullen** [comment]
@vrajmohan I believe we should close this issue since it relates to the previous codebase. Do you agree?

**Comment by vrajmohan** [comment]
Agreed.
