### ISSUE TITLE
Use tabular poverty level income for homogeneous pay period

### ISSUE THREAD

**Issue by catherinedevlin** [18F/eligibility-rules-service#69]
It turns out that annualizing all income amounts isn't quite good enough; when all incomes from a given recipient are over the same pay period (weekly, monthly, etc.), values from that column in INCOME ELIGIBILITY GUIDELINES table should be used instead.

**Comment by edmullen** [comment]
@catherinedevlin This story is in our backlog. Is there value in keeping it in the backlog for the future or not?

**Comment by edmullen** [comment]
@vrajmohan I believe we should close this issue since it relates to the previous codebase. Do you agree?

**Comment by edmullen** [comment]
@vrajmohan I believe we should close this issue since it relates to the previous codebase. Do you agree?

**Comment by vrajmohan** [comment]
Agreed.
