### ISSUE TITLE
Figure our repo approach

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#77]
With the [new D-SNAP rules and python approach](https://github.com/18F/new_rules), we have three repos. This main project repo, the WIC form, and the D-SNAP/Python repo. We need to have a clear approach for how people can follow the work as it progresses. 

I'd like to retain this repo as the primary project repo. It's got a number of people watching/starring it and our blog posts point to it. I'm not sure what the implications are for the WIC/SQL code inside it or the D-SNAP/Python in a separate one.

**Comment by vrajmohan** [comment]
Moved `new_rules` to a repo called `dsnap_rules`. We can always extract the generic rules code from D-SNAP at a later date. Similarly, I will extract WIC code (including form) into a separate repo called `wic_rules`.

**Comment by edmullen** [comment]
This work has been merged.
