### ISSUE TITLE
Come to clear, shared understanding of Phase 3 goals

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#82]
Vraj and Ed need to come to a common understanding of our goals for this phase of work. In particular

- [ ] What we hope to achieve by end of December
- [ ] What we hope to achieve by end of Phase 3

We will document our goals on the Google Drive README: https://docs.google.com/document/d/1qJ6Hq2xaf40IR258HwiURxm3A7y8mAbiWNQtfkURjhA/edit#heading=h.4hy1kvrv89fb

**Comment by vrajmohan** [comment]
We have a common understanding of the MVP for:
- API service
- Registration app
