### ISSUE TITLE
Address validation requirements

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#84]
Vraj has a hunch that address validation may be one of the significant problems with eligibility determination

**Research question:** _Is address validation that a residence is in the defined disaster area within scope?_

**Comment by vrajmohan** [comment]
As background, we have been told that:
- some disasters cover entire counties
- some cover specific zip codes within counties
- some cover specific census tracts
- some cover specific streets (e.g. in the case of tornadoes)

**Comment by edmullen** [comment]
On Nov 21, we determined with partner not to pursue this at this point.

**Comment by vrajmohan** [comment]
For the Phase 3 MVP, we will only validate that the county for the address is a valid county for the state.
