### ISSUE TITLE
Variation across states / customization requirements

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#85]
For the WIC version prototype, we were able to build out rules for an example state that varied from the federal baseline.

Research question:** _For D-SNAP, how does state-to-state variation look?_

We will need to gather Florida's rules as well as some other state examples.

**Comment by edmullen** [comment]
@vrajmohan Do you feel we have a good enough understanding of this to close the issue?

**Comment by vrajmohan** [comment]
The variations we have seen are:
1. Different DGIL tables
2. Use of DSED
3. Allowing applicants who worked in the disaster area or not.
4. Use of food loss alone as a qualifier.
