### ISSUE TITLE
Conduct contextual inquiry in Florida

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#86]
Ed will be visiting Florida to observe the application period for the Hurricane Michael D-SNAP. the trip will include:

- Visiting the Gadsen site to observe in-person application
- Visiting the Tallahassee site to observe exception processing.

**AC:**

- [x] Both sites have been visited
- [ ] Notes have been compiled into sharable form
- [ ] Key insights will be documented
- [ ] Actions based on research have been documented as new cards in the Phase 3 Project

**Comment by vrajmohan** [comment]
No need to do any more on this.
