### ISSUE TITLE
Schedule research sessions with partners

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#87]
During this discovery phase, we need to conduct research with our partners at the federal, regional, and state levels.

**AC:**

- [x] 4 sessions w National Office
- [x] 4 sessions w SERO
- [ ] 4 sessions w FL DCF
- [ ] 4 sessions w 2nd Region
- [ ] 4 sessions w 2nd State

**Comment by vrajmohan** [comment]
The work remaining is captured in #112, #118 and #95.
