### ISSUE TITLE
Where you lived on [date]

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#90]
I've seen in some of the disasters there is a specific date that they are checking for residency for. So while the benefit period is a range during which you incur expenses, the residency requirement is either always or sometimes a specific day. And it may or may not be the first day of the benefit period. 

So more questions to ask.

**Comment by vrajmohan** [comment]
Discussed in https://docs.google.com/document/d/1PhDZCQxWjOvLj3ZvzINTKfbg-xqsNFQB949nEsmN6SE/edit#heading=h.ep67yeeq28ma:
> Is the start date of the benefit period sufficient as the single date of when "the disaster struck" for determination of eligibility through the residence or work rules? Could it span 2 or more days? Do we ever need to track these separately? 
> The “disaster struck” date or the date of mandatory evacuation will always be the start date of the benefit period. That is the date that should be used to establish residence/work rules and the constitution of the household. We should however allow for multiple benefit periods. (Last January, California wildfires were followed by mudslides a few days later, that was caused by the wildfires. There was a single FR# but with multiple benefit periods.) The application should state which benefit period they are applying under.
