### ISSUE TITLE
Identify Florida's deployment options (cloud provider)

### ISSUE THREAD

**Issue by vrajmohan** [18F/eligibility-rules-service#95]
This will be the primary target deployment environment for the Registration app. @edmullen, can you please document the concerns that you had when we discussed this story?

**Comment by vrajmohan** [comment]
Met with DCF IT team for the first time on Friday, Feb 15. It appears that they have no capacity (no personnel or infrastructure) to deploy a test version of the registration app in their cloud infrastructure. All they can offer currently is some technical guidance on requirements.

**Comment by vrajmohan** [comment]
We are examining the alternative of hosting the registration app (in addition to the rules service) on cloud.gov. For the testing at the end of Phase 3, PII will not be an issue as we will use fake test data.
@edmullen, can we close this issue?

**Comment by edmullen** [comment]
I think we should keep it open until we can circle back with Eliot in the coming days following his talk with leadership. But I don't think additional work remains unless that is a no go.

**Comment by edmullen** [comment]
After discussions with partners, Florida, National Office, and 18F have agreed that the best approach to proceed with regarding deployment that reduces the need for state technical resources will be to host the registration application at the federal government utilizing Cloud.gov.
